nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "8080:8080"
node1:
    build: ./nodejs
    ports:
        - "9000:9000"
node2:
    build: ./httpd
    ports:
        - "8090:8090"
